Added installation instructions for client
IceKhan13/purplecaffeine pull request #104
Opened 2023-09-01 01:39 UTC by mentesniker

### Summary
Added installation instructions  for client code

### Details and comments

2023-09-01 07:11 UTC, mickahell reviewed
Maybe better like this

2023-09-01 07:11 UTC, mickahell commented on client/README.md
> +```
```suggestion
If you want to install from source code, execute while in the root folder of the project:


```shell
pip install client/.
```
```

2023-09-02 04:21 UTC, IceKhan13 requested changes
Can we do, something like

### Installation

Using pip:
```shell
pip install purplecaffeine
```

From sourcecode:
```shell
cd client
pip install .
```

? it will cover both cases

2023-09-03 02:43 UTC, mentesniker reviewed
I added additional instructions on the qucikstart section to include pip install purple caffeine

2023-09-03 08:28 UTC, mickahell requested changes

2023-09-03 08:28 UTC, mickahell commented on client/README.md
> +cd ./client
```suggestion
cd client
```
A cd with ./ is very uncommon

2023-09-03 21:09 UTC, IceKhan13 approved these changes
Thank you!

2023-09-03 21:10 UTC, merged