API backend: Docker
IceKhan13/purplecaffeine pull request #42
Opened 2023-05-18 12:13 UTC by mickahell

### Summary
Create the Docker image for production.
Add CI for building test.

### Details and comments
- [x] Create Dockerfile
- [ ] Docker CI

---
Closes #16 
Closes #18

2023-05-19 21:17 UTC, mickahell commented
@IceKhan13 ready for review :) I couldn't test the CI

2023-05-20 14:01 UTC, IceKhan13 requested changes
We can actually use your action too. Let's just remove on push and we are good to go!

2023-05-20 14:01 UTC, IceKhan13 commented on .github/workflows/api_server-dockerhub-release.yml
> +  push:
Let's not push on tag for now and leave only workflow dispatch. Let's try to do couple of times manually and then we will switch to automatic pushes one we tested it manually first.

Let's use this action https://github.com/marketplace/actions/docker-build-push-action
It is much cleaner and doing everything for us.

2023-05-20 21:11 UTC, mickahell commented
@IceKhan13 ready 🚀 
I didn't knew this action, but it seems I'm doing exactly the same stuff. Even for tagging and version ^^
Anyway if it's ok to use like mine I delete the push option :)

2023-05-21 02:17 UTC, IceKhan13 approved these changes
🚀

2023-05-21 02:18 UTC, merged