Implemented query search for client
IceKhan13/purplecaffeine pull request #62
Opened 2023-05-29 03:33 UTC by AnsahMohammad

### Summary

Implemented query search for client

- [ ] Implemented Search
- [ ] Added test in test_backend

### Details and comments
Currently, uses `trial.name.find(query)` to filter out all trials that contain the substring 'query' in their names.

2023-05-29 09:33 UTC, mickahell requested changes
Some tricks/logics to apply but the `find` seems to be a good way to go :)

I'm wondering maybe, having query apply on the field `tag` could also be usefull

2023-05-29 09:33 UTC, mickahell commented on client/purplecaffeine/core.py
> +        if query:
The problem here is you applied your query after the limit offset. We should be able to apply the limit to the list return by the query

2023-05-29 09:33 UTC, mickahell commented on client/tests/test_backend.py
> +        list_trials = self.local_storage.list(query="trial999")
We should test that we get a response that nothing was found by a message or raise an error. Up to you to choose :)

2023-05-30 16:42 UTC, mickahell reviewed
Good to me :) just don't we wanted to also have the query applied to the tags ?

2023-05-30 16:43 UTC, mickahell approved these changes

2023-05-30 19:54 UTC, IceKhan13 approved these changes
another hit for UX 🚀

2023-05-30 19:54 UTC, IceKhan13 commented
@AnsahMohammad can you resolve conflict?

2023-06-04 03:24 UTC, AnsahMohammad commented
@IceKhan13 extended the query to include search on tags and description.

2023-06-05 14:05 UTC, IceKhan13 requested changes

2023-06-05 14:05 UTC, IceKhan13 commented on client/purplecaffeine/core.py
> +                logging.warning("No Trials returned for the query '%s'.", query)
I think we should return empty results if nothing has been found :) 

Error will scare people :)

2023-06-05 14:35 UTC, AnsahMohammad commented
Okay, fixed that 😄

2023-06-05 15:45 UTC, IceKhan13 commented
tests are failing :)

2023-06-05 16:03 UTC, AnsahMohammad commented
@IceKhan13 Fixed tests! There was a typo!

2023-06-05 16:29 UTC, IceKhan13 approved these changes
Merging!

2023-06-05 16:30 UTC, merged